[client]
showErrorDetails = false
toolbarMode = "minimal"
showSidebarNavigation = false

[server]
address = "localhost"
headless = true
fileWatcherType = "none"
runOnSave = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
